# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [55]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [ ]:
np.__version__

In [ ]:
np.show_config()

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [ ]:
a=np.zeros((1,10))
print(a)
b=np.zeros((2,5))
print(b)

#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [ ]:
print("Size of the array: ",a.size)
print("Memory size of one array element in bytes: ", a.itemsize)
print("Memory size of numpy array in bytes:", a.size * a.itemsize)


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [ ]:
documentation=np.info()
documentation

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [ ]:
a=np.zeros((1,10))
a[0][4]=1
print(a)
b=np.zeros(10)
b[4]=1
print(b)

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [ ]:
a=np.arange(10,49,1)
a

In [ ]:
l=[]
for i in range(10,49):
  l.append(i)
a=np.array(l)
a

#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [ ]:
a=[1,2,3,4,5,6]
a=a[::-1]
a

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [ ]:
a=np.arange(0,9,1)
b=a.reshape((3,3))
b

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [ ]:
a=np.array([1,2,0,0,4,0])
np.nonzero(a)

#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [ ]:
np.eye(3)


#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [ ]:
np.random.random((3,3,3))

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [ ]:
a=np.random.random((10,10))
print("max value is: ",a.max())
print("min value is: ",a.min())

#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [ ]:
a=np.random.random(30)
print("mean value is: ",a.mean())

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [ ]:
a=np.ones((5,5))
a[1:-1,1:-1]=0
a

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [ ]:
a=np.random.random((2,2))
b=np.pad(a, pad_width=1,  mode='constant')
b

#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [ ]:
0 * np.nan


In [ ]:
np.nan == np.nan


In [ ]:
np.inf > np.nan


In [22]:
np.nan - np.nan


nan

In [23]:
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [24]:
np.diag(1+np.arange(4),k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [25]:
b=np.diag(1+np.arange(5))
b

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [26]:
a=np.zeros((8,8),dtype=int)
a[::2,1::2]=1
a[1::2,::2]=1
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [27]:
s=np.random.random((6,7,8))
s

array([[[0.62226126, 0.63531372, 0.9578513 , 0.73705858, 0.5618253 ,
         0.92189683, 0.67897915, 0.09345917],
        [0.59040874, 0.64702856, 0.54913077, 0.06800953, 0.35321387,
         0.66987725, 0.28609495, 0.83752452],
        [0.0875796 , 0.40144309, 0.31133442, 0.88720921, 0.54882438,
         0.60409397, 0.64386193, 0.08493478],
        [0.02363523, 0.46474922, 0.71777815, 0.7854038 , 0.28107309,
         0.57433547, 0.53511421, 0.41917834],
        [0.57577159, 0.51284439, 0.95617578, 0.88713054, 0.11559859,
         0.08782811, 0.99810564, 0.09774065],
        [0.2234804 , 0.42488035, 0.39595971, 0.5754017 , 0.00420345,
         0.10233503, 0.20775877, 0.1124563 ],
        [0.95271678, 0.90267167, 0.56723475, 0.7830014 , 0.78322684,
         0.15122743, 0.25548855, 0.94171539]],

       [[0.93469936, 0.2558099 , 0.84059373, 0.175965  , 0.34177912,
         0.14020592, 0.13325762, 0.08050382],
        [0.70195865, 0.37840116, 0.03408096, 0.04750931, 0.2111056 ,
         

In [28]:
np.unravel_index(100,(6,7,8))

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [29]:
a = np.array([0, 1, 2])
np.tile(a, 2)

array([0, 1, 2, 0, 1, 2])

In [30]:
np.tile(a, (2, 2))

array([[0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2]])

In [31]:
np.tile(a, (2, 1, 2))

array([[[0, 1, 2, 0, 1, 2]],

       [[0, 1, 2, 0, 1, 2]]])

In [32]:
b = np.array([[1, 2], [3, 4]])
np.tile(b, 2)

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [33]:
np.tile(b, (2, 1))

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [34]:
np.tile(b, (2, 2))

array([[1, 2, 1, 2],
       [3, 4, 3, 4],
       [1, 2, 1, 2],
       [3, 4, 3, 4]])

In [35]:
c = np.array([1,2,3,4])
np.tile(c,(4,1))

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [36]:
np.tile(c,(2,3))

array([[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4],
       [1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]])

In [37]:
np.tile(c,(3,2))

array([[1, 2, 3, 4, 1, 2, 3, 4],
       [1, 2, 3, 4, 1, 2, 3, 4],
       [1, 2, 3, 4, 1, 2, 3, 4]])

In [38]:
b = np.array([[0, 1], [1, 0]])
c=np.tile(b, (4,4))
c

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [39]:
c.shape

(8, 8)

#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [40]:
y=np.random.randint(1,101,25)
x=np.reshape(y,(5,5))
x

array([[24, 38, 11, 75, 58],
       [85, 95, 33, 53, 57],
       [47, 10, 51, 61, 77],
       [91, 85, 80, 48, 57],
       [31, 83, 49, 22, 16]])

In [41]:
min=x.min()
max=x.max()
print((x - min) / (max - min))

[[0.16470588 0.32941176 0.01176471 0.76470588 0.56470588]
 [0.88235294 1.         0.27058824 0.50588235 0.55294118]
 [0.43529412 0.         0.48235294 0.6        0.78823529]
 [0.95294118 0.88235294 0.82352941 0.44705882 0.55294118]
 [0.24705882 0.85882353 0.45882353 0.14117647 0.07058824]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [42]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
color

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  after removing the cwd from sys.path.


dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [43]:
a=np.random.random((5,3))
b=np.random.random((3,2))
np.dot(a, b, out=None)

array([[0.54727382, 1.45688887],
       [0.25577341, 0.49166885],
       [0.45349031, 1.47142019],
       [0.57849384, 1.34787827],
       [0.52018791, 1.09413185]])

In [44]:
a=np.random.randint(1,16,15).reshape(5,3)
b=np.random.randint(1,7,6).reshape(3,2)
a.dot(b)

array([[ 46,  26],
       [ 56,  20],
       [ 88,  36],
       [135,  65],
       [ 75,  41]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [45]:
a = np.arange(11)
a[(3 < a) & (a <= 8)] *= -1
print(a)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [46]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

In [47]:
z = np.arange(11)
z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [48]:
2 << z >> 2

array([  0,   1,   2,   4,   8,  16,  32,  64, 128, 256, 512])

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [49]:
np.array(0) / np.array(0)


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


nan

In [50]:
np.array(0) // np.array(0)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


0

In [51]:
np.array([np.nan]).astype(int).astype(float)

array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [52]:
Z = np.random.uniform(1,10,10)
print (np.copysign(np.ceil(np.abs(Z)), Z))

[ 8.  3.  7.  8.  9.  9. 10.  8.  4.  5.]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [53]:
a=np.random.randint(1,10,10)
b=np.random.randint(1,10,10)
np.intersect1d(a,b)

array([2, 3, 4, 5, 6, 9])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [54]:
np.seter(all='ignore')

AttributeError: ignored

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1)

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [ ]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [ ]:
print(np.arange('2016-07', '2016-08', dtype='datetime64[D]'))

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [ ]:
a=np.ones(3)*1
b=np.ones(3)*2
c=np.ones(3)*3



In [ ]:
add=np.add(a,b)
add

In [ ]:
negate=np.negative(a)
negate

In [ ]:
div=np.divide(negate,2)

In [ ]:
multi=np.multiply(add,div)
multi

In [ ]:
np.add(a,b,out=b)
np.divide(a,2,out=a)
np.negative(a,out=a)
np.multiply(a,b,out=a)

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [ ]:
a=np.random.uniform(1,10,20)
a

In [ ]:
a-a%1

In [ ]:
np.floor(a)

In [ ]:
np.ceil(a)

In [ ]:
a.astype(int)

In [ ]:
np.trunc(a)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [ ]:
a=np.random.randint(0,4,25)
a

In [ ]:
a.reshape(5,5)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [ ]:
l=[]
for i in range(10):
  l.append(i)
a=np.fromiter(l,dtype=float)
a


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [ ]:
np.linspace(0,1,11,endpoint=False)[1:]

#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [ ]:
a=np.random.random(10)
np.sort(a)

#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [ ]:
a=random.randint(1,10,10)


In [ ]:
np.add.reduce(a)

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [ ]:
a=np.arange(10)
b=np.arange(10)
c=np.arange(11)

In [ ]:
np.array_equal(a,b)

In [ ]:
np.allclose(a,b)

In [ ]:
np.array_equal(a,c)

#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [ ]:
a = np.zeros(10)
a.flags.writeable = False
a[0]=1

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [ ]:
Z=random.random((10,2))
X, Y = Z[:, 0], Z[:, 1]
R = np.sqrt(X * 2 + Y * 2)
T = np.arctan2(Y, X)
print(R)
print(T)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [ ]:
a=np.random.random(10)


In [ ]:
a.max()

In [ ]:
np.argmax(a)

In [ ]:
a[np.argmax(a)]=0
a

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [ ]:
data= [('x',float),('y',float)]

In [ ]:
w=5

In [ ]:
a = np.zeros((w,w),dtype=data)
a

In [ ]:
a['x'], a['y'] = np.meshgrid(np.linspace(0,1,w), np.linspace(0,1,w))


In [ ]:
a['x']

In [ ]:
a['y']

In [ ]:
print(a)

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [ ]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [ ]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)

In [ ]:
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)

#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [ ]:
np.set_printoptions(precision=4)
np.array([1.123456789])

In [ ]:
np.set_printoptions(threshold=5)
np.arange(100)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [ ]:
a = np.arange(100)
a

In [ ]:
b=np.random.uniform(0,100)
b

In [ ]:
c=np.abs(a-b)
c

In [ ]:
index=np.argmin(c)
index

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [ ]:
a= np.ones((3,3), [ ('position', [ ('x', float, 1), ('y', float, 1)]),                                 
                   ('color',    [ ('r', float, 1),('g', float, 1),('b', float, 1)])])
                                
print(a)                                                              


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [ ]:
a=np.random.random((2,100)).reshape(100,2)
a

In [ ]:
x,y=np.atleast_2d(a[:,0],a[:,1])
x,y

In [ ]:
hypo=np.sqrt((x-x.T)**2 + (y-y.T)**2)
hypo

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [ ]:
a=np.arange(10,dtype=int32)
a

In [ ]:
a=np.arange(10,dtype=int32)
a=a.astype(np.float32,copy= False)
a

#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
from io import StringIO
a = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n
                            """)
b=np.genfromtxt(a, delimiter=",")
b

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [ ]:
l=[1,2,3,4]
a=np.array(l)
for i in np.ndenumerate(a):
  print(i)
for i in np.ndindex(a.shape):
  print(i,a[i])


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [ ]:
x= np.linspace(-5,5,200)
x

In [ ]:
sigma, mu = 1.0, 0.0
d = 1/((np.sqrt(2*np.pi))*sigma)
d

In [ ]:
g=[]
for i in np.nditer(x):
  t=(np.exp(-(0.5*((i-mu)/(sigma))**2)))*d
  g.append(t)
g=np.array(g)
g

In [ ]:
import matplotlib.pyplot as plt


In [ ]:
plt.plot(x,g)

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [ ]:
a=range(5*5)
a

In [ ]:
n = 5
a=range(n*n)
p = 9
Z = np.ones((n,n))
np.put(Z, np.random.choice(a, p, replace=False),0)
print(Z)

#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [ ]:
a=np.random.rand(3,4)
a

In [ ]:
mean=np.mean(a, axis=1 , keepdims=True)
mean

In [ ]:
b = a - mean
b

#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [ ]:
a= np.random.randint(0,10,(3,3))
a

In [ ]:
print(a[a[:,0].argsort()])

#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [ ]:
a=np.random.randint(0,3,(3,5))
a

In [ ]:
print(a.any(axis=0))

In [ ]:
print(~a.any(axis=0))

In [ ]:
print(~a.any(axis=0).any())

#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [ ]:
#already solved in #50

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [57]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [58]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [59]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)
np.add.at(Z, I, 1)
print(Z)

[4. 4. 1. 5. 2. 3. 2. 1. 5. 3.]
[7. 7. 1. 9. 3. 5. 3. 1. 9. 5.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [60]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [61]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(np.unique(I))

[0 1]


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [62]:
A = np.random.randint(0,10,(3,4,3,4))
sum = A.sum(axis=(-2,-1))
print(sum)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[44 63 60 65]
 [47 63 63 58]
 [34 29 54 83]]
[[44 63 60 65]
 [47 63 63 58]
 [34 29 54 83]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [63]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.50409906 0.39997518 0.47469523 0.46240293 0.50565018 0.48897658
 0.54182195 0.57629797 0.38311268 0.46425611]


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [64]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
np.diag(np.dot(A, B))

array([2.56089313, 1.50973413, 1.51959188, 1.05394032, 0.73533613])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [65]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [66]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [67]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [68]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 1, 31) ( 1, 85) ( 2, 24) ( 2, 98) ( 3, 37) ( 3, 92) ( 5, 46) ( 5, 88)
 (12, 58) (12, 82) (13, 16) (13, 35) (13, 93) (16, 93) (19, 68) (19, 74)
 (23, 34) (23, 61) (24, 98) (31, 85) (34, 61) (35, 35) (37, 92) (46, 88)
 (58, 82) (68, 74) (80, 95) (80, 98) (95, 98)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [69]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [70]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [71]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [72]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([ 0.74911648, -0.82009691,  0.92807255,  0.09477654,  0.00761217,
       -0.56555533,  0.30057612, -0.28763403, -0.30203237, -0.30516251,
       -0.25414375,  0.81110356, -0.24388091,  0.29626473,  0.06343738,
       -0.54313117,  0.47987949, -0.11494578, -0.81402485,  0.38253757,
       -0.08534294, -0.33106174,  0.31831433, -0.8944854 ,  0.64171161,
       -0.43400694, -0.58673449, -0.06314878,  0.1967201 ,  0.70818984,
        0.31430759, -0.43207372, -0.94911769,  0.97855097,  0.1011005 ,
        0.71320736, -0.99574484,  0.02497048, -0.84528336,  0.66255526,
        0.15092589, -0.88003212,  0.96494581,  0.81924238,  0.4766767 ,
        0.10906626,  0.29634424,  0.5924229 , -0.6122555 ,  0.98325494,
       -0.40825873, -0.03423632,  0.22678201, -0.87695248, -0.01530367,
       -0.50251261,  0.54881234, -0.16087418, -0.01610235,  0.80716839,
        0.70512738,  0.10604507, -0.45379422,  0.95522998,  0.29780832,
       -0.46512158,  0.69055827,  0.28243437, -0.27818964, -0.29

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [73]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[11.79674402  3.30742782 12.1544747   5.63582059 10.12609848  5.56111597
  0.91389889  4.55210084  9.20585257  8.75192092]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [74]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[10.93285925 16.21897997  7.68678083 17.9586782  10.68241613  8.38254384
  16.96509726 17.95125854  2.94529575  7.95042114]
 [ 5.4261336   9.0147783   4.15622175  4.4932302  12.52886628  5.51570827
   4.89580578  9.4593718  12.11815768 11.03190341]
 [ 1.81736466  4.20049608  1.73521533  2.74951733  5.68845819  0.24396788
   2.25961001  5.1217012   5.19593094  4.07278321]
 [ 0.13744634  2.44403915  9.06461347  1.30394122  1.9195903   4.77753232
   2.61124026  1.16855755  1.39507668  3.48481028]
 [ 3.04170416 16.02003331 10.87409838 10.840029   18.24242591  5.99509665
  11.58267716 16.47324582 15.33689315 16.4224782 ]
 [ 2.04162072 10.71577354  5.10594652  7.43407719 12.35834368  2.72885577
   7.56701726 11.42044612 10.38143027 10.60081089]
 [ 5.74203798  0.91817191  6.99052253  4.10465786  1.80664897  9.4474449
   2.36613126  2.63320893  4.10049621  3.83430204]
 [ 3.4673771   1.76199199  5.55901462  3.59099147  0.30415376  6.7385857
   2.21505055  3.24248655  1.41319968  1.59607966]
 [

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [75]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[4 9 5 6 4 1 3 6 4 1]
 [0 4 3 2 3 5 4 5 3 9]
 [2 1 6 2 2 7 8 4 3 5]
 [2 8 4 9 2 0 5 8 9 3]
 [9 4 0 8 3 4 4 5 1 1]
 [1 4 9 6 7 1 5 7 6 2]
 [3 8 5 1 3 1 6 7 5 2]
 [0 0 1 5 7 5 5 7 8 0]
 [7 6 6 2 4 7 7 3 3 2]
 [1 2 6 5 5 6 0 0 5 5]]
[[0 0 0 0 0]
 [0 4 9 5 6]
 [0 0 4 3 2]
 [0 2 1 6 2]
 [0 2 8 4 9]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [76]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [77]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [78]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

5


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [79]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[0 0 1]
   [1 1 4]
   [0 3 4]]

  [[0 1 1]
   [1 4 1]
   [3 4 0]]

  [[1 1 4]
   [4 1 1]
   [4 0 0]]

  [[1 4 2]
   [1 1 4]
   [0 0 2]]

  [[4 2 4]
   [1 4 2]
   [0 2 3]]

  [[2 4 0]
   [4 2 3]
   [2 3 2]]

  [[4 0 3]
   [2 3 0]
   [3 2 3]]

  [[0 3 3]
   [3 0 0]
   [2 3 4]]]


 [[[1 1 4]
   [0 3 4]
   [1 2 4]]

  [[1 4 1]
   [3 4 0]
   [2 4 4]]

  [[4 1 1]
   [4 0 0]
   [4 4 0]]

  [[1 1 4]
   [0 0 2]
   [4 0 2]]

  [[1 4 2]
   [0 2 3]
   [0 2 3]]

  [[4 2 3]
   [2 3 2]
   [2 3 3]]

  [[2 3 0]
   [3 2 3]
   [3 3 3]]

  [[3 0 0]
   [2 3 4]
   [3 3 1]]]


 [[[0 3 4]
   [1 2 4]
   [1 1 2]]

  [[3 4 0]
   [2 4 4]
   [1 2 1]]

  [[4 0 0]
   [4 4 0]
   [2 1 3]]

  [[0 0 2]
   [4 0 2]
   [1 3 2]]

  [[0 2 3]
   [0 2 3]
   [3 2 4]]

  [[2 3 2]
   [2 3 3]
   [2 4 3]]

  [[3 2 3]
   [3 3 3]
   [4 3 3]]

  [[2 3 4]
   [3 3 1]
   [3 3 4]]]


 [[[1 2 4]
   [1 1 2]
   [1 4 4]]

  [[2 4 4]
   [1 2 1]
   [4 4 0]]

  [[4 4 0]
   [2 1 3]
   [4 0 2]]

  [[4 0 2]
   [1 3 2]
   [0 2 3]]

  [[0 2 3]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [80]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 5 12  8  3 17]
 [12  4 11 14  6]
 [ 8 11  9 42  7]
 [ 3 14 42  4  7]
 [17  6  7  7  2]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [81]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [82]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [83]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [84]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print (Z[np.argsort(Z)[-n:]])

[9995 9996 9997 9998 9999]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [85]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [87]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T, 
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [89]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[1 2 6]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [90]:
Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[3 4 3]
 [2 1 1]
 [4 2 0]
 [4 3 3]
 [1 3 4]
 [4 2 4]
 [1 0 4]
 [3 4 4]
 [0 4 4]
 [1 0 3]]
[[3 4 3]
 [2 1 1]
 [4 2 0]
 [4 3 3]
 [1 3 4]
 [4 2 4]
 [1 0 4]
 [3 4 4]
 [0 4 4]
 [1 0 3]]
[[3 4 3]
 [2 1 1]
 [4 2 0]
 [4 3 3]
 [1 3 4]
 [4 2 4]
 [1 0 4]
 [3 4 4]
 [0 4 4]
 [1 0 3]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [91]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [92]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 0]
 [0 1 0]
 [0 1 1]
 [1 0 1]
 [1 1 0]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [93]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       
np.einsum('i,i->i', A, B)
np.einsum('i,i', A, B)   
np.einsum('i,j->ij', A, B)

array([[0.03433513, 0.01546336, 0.01546605, 0.00233452, 0.0269758 ,
        0.03977398, 0.03764212, 0.03195237, 0.00835865, 0.00978882],
       [0.80192254, 0.36115829, 0.36122107, 0.05452455, 0.63003983,
        0.92895084, 0.8791597 , 0.74627152, 0.19522258, 0.2286252 ],
       [0.17747547, 0.07992884, 0.07994274, 0.01206696, 0.13943568,
        0.20558842, 0.19456902, 0.16515921, 0.04320519, 0.05059761],
       [0.68149383, 0.30692134, 0.3069747 , 0.04633633, 0.53542361,
        0.78944566, 0.7471319 , 0.6342002 , 0.16590503, 0.19429141],
       [0.75453244, 0.33981542, 0.33987449, 0.05130239, 0.59280724,
        0.87405392, 0.82720522, 0.70217015, 0.18368578, 0.21511445],
       [0.10567321, 0.04759157, 0.04759985, 0.00718496, 0.0830234 ,
        0.12241235, 0.11585113, 0.09833981, 0.02572542, 0.03012705],
       [0.18954731, 0.08536558, 0.08538042, 0.01288776, 0.14892006,
        0.21957249, 0.20780355, 0.17639329, 0.046144  , 0.05403925],
       [0.6765765 , 0.30470675, 0.3047597

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [95]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [96]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [97]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.29523396  0.06815112]
